export const userApi = "http://localhost:9000/chronica-user/api"
export const linksApi = "http://localhost:9000/api/links"
export const groupsApi = "http://localhost:9000/api/groups"
export const projectsApi = "http://localhost:9000/api/projects"
export const chainsApi = "http://localhost:9000/api/chains"
export const notificationsApi = "http://localhost:9000/api/notifications"
export const snapsApi = "http://localhost:9000/api/snaps"