export const accountsApi = "http://localhost:9000/api/accounts"
export const linksApi = "http://localhost:9000/api/links"
export const groupsApi = "http://localhost:9000/api/groups"
export const projectsApi = "http://localhost:9000/api/projects"
export const notificationsApi = "http://localhost:9000/api/notifications"